### ISSUE TITLE
Issue with LaTeX installation guide

### ISSUE THREAD

**Issue by alexhang212** [Imperial-FoNS-Computing/FoNS-installation-instructions#13]
For the ubuntu installation guide, the code shows "sudo apt-install texlive-latex-extra", but this should be a typo, the dash between 'apt' and 'install' should be a space instead. Should be "sudo apt install texlive-latex-extra"

**Comment by dham** [comment]
You are absolutely correct. Thanks for catching this. I have updated the instructions accordingly. It might take a few minutes to filter through to the website due to caching effects.
